version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventbridge-apidestinations"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h94b2r98fa8u"
s3_prefix = "eventbridge-apidestinations"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiDestinationUrl=\"https://j64t4zpedg.execute-api.eu-west-1.amazonaws.com/live/pets\""
