version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventbridge-inside-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h94b2r98fa8u"
s3_prefix = "eventbridge-inside-aws"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
